export * from "./Header"
export * from "./TargetAudience"
export * from "./Teacher"
export * from "./WhatCourseContain"
export * from "./Support"
export * from "./Employment"
export * from "./Result"
export * from "./Rates"
